# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fits a Latent Space Model for a Dynamic Network
#' 
#' @param Y The adjacency matrix for each network, 
#'  shape (n_time_points, n_nodes, n_nodes)
#' @return
#' @export
fit_latent_space_network <- function(Y, num_dimensions, num_iter, num_burn_in, seed) {
    .Call(`_lsmdn_fit_latent_space_network`, Y, num_dimensions, num_iter, num_burn_in, seed)
}

