# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fits a Procrustes Transformation
#' @export
procrustes <- function(X, Y) {
    .Call(`_lsmdn_procrustes`, X, Y)
}

#' Samples from an Inverse Gamma Distribution.
#'
#' Note that you must change the seed per draw to get different values.
#' This is exposed for testing purposes and should not be used in R code.
#'
#' @export
rinvgamma <- function(num_samples, shape, scale = 1, seed = 123L) {
    .Call(`_lsmdn_rinvgamma`, num_samples, shape, scale, seed)
}

#' Samples from a Dirichlet Distribution.
#'
#' Note that you must change the seed per draw to get different values.
#' This is exposed for testing purposes and should not be used in R code.
#'
#' @export
rdirichlet <- function(num_samples, alphas, seed = 123L) {
    .Call(`_lsmdn_rdirichlet`, num_samples, alphas, seed)
}

#' Calculates the log-likelihood of the latent space network model.
#'
#' @export
lsmdn_log_likelihood <- function(Y, X, radii, beta_in, beta_out) {
    .Call(`_lsmdn_lsmdn_log_likelihood`, Y, X, radii, beta_in, beta_out)
}

#' Calculates the log-likelihood of the latent space network model.
#'
#' @export
lsmdn_grad_beta <- function(Y, X, radii, beta_in, beta_out) {
    .Call(`_lsmdn_lsmdn_grad_beta`, Y, X, radii, beta_in, beta_out)
}

#' Fits a Latent Space Model for a Dynamic Network
#'
#' @param Y The adjacency matrix for each network,
#'  shape (n_time_points, n_nodes, n_nodes)
#' @return
#' @export
fit_latent_space_network <- function(Y, X_init, radii_init, beta_in, beta_out, nu_in, xi_in, nu_out, xi_out, tau_sq, tau_shape, tau_scale, sigma_sq, sigma_shape, sigma_scale, num_samples, num_burn_in, step_size_x, step_size_beta, step_size_radii, seed) {
    .Call(`_lsmdn_fit_latent_space_network`, Y, X_init, radii_init, beta_in, beta_out, nu_in, xi_in, nu_out, xi_out, tau_sq, tau_shape, tau_scale, sigma_sq, sigma_shape, sigma_scale, num_samples, num_burn_in, step_size_x, step_size_beta, step_size_radii, seed)
}

