#' sample from a mixture of gaussians with equal mixture weights
#' 
#' @export
rnorm_mixture <- function(num_nodes, num_dimensions = 2, num_clusters = 5) {
    # cluster means ~ N(0, (2/n)^2 * I_p)
    prior_sigma <- (2. / num_nodes)
    mu <- prior_sigma * rnorm(num_clusters * num_dimensions)
    mu <- matrix(mu, nrow = num_clusters, ncol = num_dimensions)
    
    # sample from the mixture
    cluster_ids <- sample(1:num_clusters, num_nodes, replace = TRUE)
    
    sigma <- 1. / (5. * num_nodes)
    X <- sigma * rnorm(num_nodes * num_dimensions)
    X <- matrix(X, nrow = num_nodes, ncol = num_dimensions) + mu[cluster_ids, ]
    
    X
}

#' Generate synthetic network data generated by a LSMDN model
#' 
#' @export
synthetic_network <- function(num_nodes = 100,
                              num_time_steps = 10, 
                              num_dimensions = 2,
                              beta_in = 1, 
                              beta_out = 2,
                              seed = 42) {
    set.seed(seed)
    
    # determine latent positions
    X <- array(0, c(num_nodes, num_dimensions, num_time_steps))
    
    # initial latent positions are sampled from a mixture of normals
    X[, , 1] <- rnorm_mixture(num_nodes, num_dimensions)
    
    # apply transition equations to sample further times
    sigma <- 1. / (5. * num_nodes)
    for(t in 2:num_time_steps) {
        X[, , t] <- matrix(sigma * rnorm(num_nodes * num_dimensions), 
                           nrow = num_nodes, ncol = num_dimensions)
        X[, , t] <- X[, , t] + X[, , t - 1]
    }
    
    # sample radii
    inv_norms <- 1 / sqrt(rowSums(X[, , 1]^2))
    alphas <- (num_nodes * inv_norms) / max(inv_norms)
    radii <- as.vector(MCMCpack::rdirichlet(1, alphas))
    
    # based on this model determine the probabilities of edges forming
    Y <- array(0, c(num_nodes, num_nodes, num_time_steps))
    Y <- lsmdn_sample(Y, X, radii, beta_in, beta_out, seed)
    
    list(Y=Y, X=X, radii=radii, beta_in=beta_in, beta_out=beta_out,
         sigma_sq=sigma^2)
}